Document: bitcorder
Title: Debian bitcorder Manual
Author: <insert document author here>
Abstract: This manual describes what bitcorder is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/bitcorder/bitcorder.sgml.gz

Format: postscript
Files: /usr/share/doc/bitcorder/bitcorder.ps.gz

Format: text
Files: /usr/share/doc/bitcorder/bitcorder.text.gz

Format: HTML
Index: /usr/share/doc/bitcorder/html/index.html
Files: /usr/share/doc/bitcorder/html/*.html
